const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1450,height:1100}}),errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('file:'))requests.push(r.url());});page.on('dialog',d=>d.accept());
try{
await page.goto(pathToFileURL(path.resolve(__dirname,'../examples/menu-editor.html')).href);await page.waitForFunction(()=>document.querySelector('#feedback').textContent.includes('JSON gültig'));
assert.equal(await page.locator('#deck canvas').count(),6);assert.equal(await page.locator('#pages button').count(),29);
await page.locator('#pages button').filter({hasText:/^Rollo RoomB$/}).click();await page.selectOption('#mode','edit');await page.locator('#deck button').nth(1).click();assert.equal(await page.locator('#entity').inputValue(),'rollo.room_b');assert.equal(await page.locator('#state').inputValue(),'');assert.equal(await page.locator('#state').getAttribute('placeholder'),'Keine Statusanzeige zugeordnet');await page.click('#home');await page.selectOption('#mode','navigate');
assert.equal(await page.locator('#mode').inputValue(),'navigate');
await page.locator('#deck button').nth(1).click();await page.locator('#deck button').nth(2).click();assert.equal(await page.locator('#page-heading').textContent(),'Essz.');await page.locator('#deck button').nth(4).click();assert((await page.locator('#action-hint').textContent()).includes('licht.kueche.licht2'));await page.click('#home');
await page.locator('#pages button').filter({hasText:/^Essz\.$/}).click();assert.equal(await page.locator('#page-heading').textContent(),'Essz.');
await page.click('#home');await page.locator('#deck button').nth(1).click();await page.locator('#deck button').nth(2).click();assert.equal(await page.locator('#page-heading').textContent(),'Essz.');
await page.click('#home');await page.selectOption('#mode','edit');await page.locator('#deck button').nth(1).click();assert((await page.locator('#action-hint').textContent()).includes('Taste ausgewählt'));await page.click('#open-target');assert.equal(await page.locator('#page-heading').textContent(),'Licht');await page.click('#home');
await page.selectOption('#mode','navigate');await page.locator('#deck button').nth(1).click();assert.equal(await page.locator('#page-heading').textContent(),'Licht');await page.locator('#deck button').nth(1).click();assert.equal(await page.locator('#page-heading').textContent(),'Wohnz.');
await page.locator('#deck button').nth(1).click();assert((await page.locator('#action-hint').textContent()).includes('wird nicht gesendet'));
await page.selectOption('#mode','edit');await page.locator('#deck button').nth(1).click();const original=JSON.parse(await page.locator('#raw').inputValue());
await page.fill('#label-bottom','Testlampe');assert.equal(JSON.parse(await page.locator('#raw').inputValue()).pages.wohnzimmer.buttons.topLeft.labels.bottom,'Testlampe');
await page.selectOption('#style','on');await page.fill('#state-text','HELL');assert.equal(JSON.parse(await page.locator('#raw').inputValue()).pages.wohnzimmer.buttons.topLeft.appearance.on.center,'HELL');
assert(await page.locator('#target-wrap').isHidden());assert(await page.locator('#entity-wrap').isVisible());
await page.selectOption('#action','set');await page.fill('#value','false');await page.locator('#value').blur();assert.equal(JSON.parse(await page.locator('#raw').inputValue()).pages.wohnzimmer.buttons.topLeft.onPress.value,false);
await page.selectOption('#action','position');await page.fill('#value','101');await page.locator('#value').blur();assert(await page.locator('#export').isDisabled());
await page.fill('#value','oops');await page.locator('#value').blur();await page.selectOption('#menu-state','off');assert(await page.locator('#export').isDisabled());
await page.selectOption('#action','toggle');assert(!(await page.locator('#export').isDisabled()));
const downloadPromise=page.waitForEvent('download');await page.click('#export');const download=await downloadPromise;const saved=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(saved.pages.wohnzimmer.buttons.topLeft.labels.bottom,'Testlampe');assert.equal(saved.pages.wohnzimmer.buttons.topLeft.onPress.entity,original.pages.wohnzimmer.buttons.topLeft.onPress.entity);
await page.setInputFiles('#import',{name:'menu.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});await page.waitForFunction(()=>document.querySelector('#page-heading').textContent==='Hauptmenü');
const invalid=structuredClone(saved);invalid.pages.licht.next='missing';await page.setInputFiles('#import',{name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await page.waitForFunction(()=>document.querySelector('#feedback').classList.contains('error'));assert.notEqual(JSON.parse(await page.locator('#raw').inputValue()).pages.licht.next,'missing');
await page.click('#home');await page.selectOption('#mode','navigate');await page.locator('#deck button').nth(1).click();await page.locator('#deck button').nth(1).click();
const back=page.locator('#deck button').nth(3);const box=await back.boundingBox();await page.mouse.move(box.x+20,box.y+20);await page.mouse.down();await page.waitForFunction(()=>document.querySelector('#page-heading').textContent==='Hauptmenü');await page.mouse.up();assert.equal(await page.locator('#page-heading').textContent(),'Hauptmenü');
await page.selectOption('#mode','edit');await page.locator('#deck button').nth(1).click();await page.screenshot({path:path.resolve(__dirname,'../build/tests/editor-desktop.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.resolve(__dirname,'../build/tests/editor-mobile.png'),fullPage:true});
assert.deepEqual(errors,[]);assert.deepEqual(requests.filter(x=>!x.startsWith('blob:')),[]);
console.log('PASS: offline file, 29 pages, navigation, hold Home, visual edits, states, JSON round trip, invalid import preserved, mobile, no external requests');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
