const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
const page=await browser.newPage({viewport:{width:1450,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
await page.goto(pathToFileURL(path.resolve(__dirname,'../examples/menu-editor.html')).href);
await page.waitForFunction(()=>document.querySelector('#feedback').textContent.includes('JSON gültig'));
assert.equal(await page.locator('#deck canvas').count(),6);assert.equal(await page.locator('#pages button').count(),25);
const key=i=>page.locator('#deck button').nth(i),heading=()=>page.locator('#page-heading').textContent();
await key(0).click();assert.equal(await heading(),'Wohnz.');await key(1).click();assert.match(await page.locator('#action-hint').textContent(),/licht.wohnzimmer.decke/);
await key(3).click();assert.equal(await heading(),'Essz.');await key(5).click();assert.match(await page.locator('#action-hint').textContent(),/licht.flur/);
await key(3).click();assert.equal(await heading(),'Garten');await key(3).click();assert.equal(await heading(),'Wohnz.');await key(0).click();assert.equal(await heading(),'Hauptmenü');
await key(2).click();await key(2).click();assert.equal(await heading(),'Rollo RoomB');await key(3).click();assert.equal(await heading(),'Rollo Schlaf');await key(0).click();assert.equal(await heading(),'Rollos oben');await key(0).click();
await key(1).click();await key(3).click();assert.equal(await heading(),'Raffst. alle');await page.click('#home');
await key(3).click();await key(5).click();assert.match(await page.locator('#action-hint').textContent(),/szene.schlafenszeit trigger/);
await page.selectOption('#mode','edit');await key(0).click();assert.equal(await page.locator('#target').inputValue(),'hauptmenue');
await page.selectOption('#mode','navigate');const box=await key(3).boundingBox();await page.mouse.move(box.x+20,box.y+20);await page.mouse.down();await page.waitForFunction(()=>document.querySelector('#page-heading').textContent==='Hauptmenü');await page.mouse.up();assert.equal(await heading(),'Hauptmenü');
await page.screenshot({path:path.resolve(__dirname,'../build/tests/editor-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
console.log('PASS: six-key home, direct lights, category cycles, rollo siblings, Raffstore All, bedtime, editable navigation, hold Home, mobile');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
