#!/usr/bin/env python3
"""Generate one copy/paste ioBroker script from the editable alias JSON and tested core."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
config = json.loads((root / 'examples/iobroker-aliases.json').read_text())
core = (root / 'scripts/iobroker-bridge-core.js').read_text().split("if (typeof module")[0]
output = '// Generated by scripts/build_iobroker.py; edit examples/iobroker-aliases.json.\n'
output += '// Paste into a new ioBroker JavaScript script. This file is not deployed automatically.\n'
output += 'const STREAMDECK_CONFIG = ' + json.dumps(config, ensure_ascii=False, indent=2) + ';\n\n' + core
output += '''\nconst streamDeckBridge = createStreamDeckBridge({
    getStateAsync, getObjectAsync, setStateAsync, createStateAsync, sendTo, on, log, wait, setInterval
}, STREAMDECK_CONFIG);
streamDeckBridge.start().catch(e => log(`Stream Deck Start fehlgeschlagen: ${e.message}`, 'error'));
'''
(root / 'examples/iobroker-streamdeck.js').write_text(output)
print('Generated examples/iobroker-streamdeck.js')
